version: '2'

services:
  nginx-ldap-auth-server:
    build: .
    container_name: nginx-ldap-auth-server
    read_only: true
    ports:
     - "8088:8088"
    volumes:
     - ./config.json:/usr/src/app/config.json:ro
